### ISSUE TITLE
Error in the pre-filled Preprocess pipline.yml file

### ISSUE THREAD

**Issue by andrewkcleeuc** [DendrouLab/panpipes-tutorials#50]
For the section "[Filtering data with panpipes - running the pipeline](https://panpipes-tutorials.readthedocs.io/en/latest/filtering_data/filtering_data_with_panpipes.html#running-the-pipeline)"

The pre-filled pipeline.yml file ([here](https://panpipes-tutorials.readthedocs.io/en/latest/filtering_data/pipeline_yml.html)) contains an error on the specificed ATAC normalisation method, and needs to be updated. 

```
# ATAC preprocessing steps
# ------------------------
atac:
  binarize: False
  normalize: TFIDF  #"log1p" or "TFIDF"
```

The figures generated using this pre-filled pipeline.yml do not match the PCA plot images posted in the documentation. This is because the pre-filled YAML file uses `TFIDF`, but the plot images were generated using `log1p` .
